config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :photos
  root "photos#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
  mount_uploader :file_location, PhotoImageUploader
  validates_presence_of :photo_name, :description, :file_location, :tag, :date
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, :only => [:show, :edit, :update, :destroy]
  
  # show all photos
  def index
    @photos = Photo.all
  end

  # add new photo
  def new
    @photo = Photo.new
  end

  # create new photo data
  def create
    @photo = Photo.new(photo_params)
    if @photo.save
      redirect_to photos_url
    else
      render :action => :new
    end
  end

  def update
    if @photo.update_attributes(photo_params)
      redirect_to photo_path(@photo)
    else
      render :action => :edit
    end
  end

  def destroy
    @photo.destroy

    redirect_to photos_url
  end

  private

  # 透過 params 取得表單來的資料
  def photo_params
    params.require(:photo).permit(:photo_name, :date, :description, :file_location, :tag)
  end

  def set_photo
    @photo = Photo.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhotoAlbum</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/photos/_form.html.erb
<!-- error message -->
<% if @photo.errors.present? %>
  <ul>
    <% @photo.errors.each do |error, message| %>
      <li><%= "#{error.capitalize} #{message}" %></li>
    <% end %>
  </ul>
<% end %>

<!-- form -->
<%= form_for @photo do |f| %>
  <%= f.label :photo_name, "Title" %>
  <%= f.text_field :photo_name %>

  <%= f.label :date, "Date" %>
  <%= f.text_field :date %>

  <%= f.label :description, "Description" %>
  <%= f.text_area :description %>

  <%= f.label :file_location, "File Location" %>
  <%= f.file_field :file_location %>

  <%= f.label :tag, "Tag" %>
  <%= f.text_field :tag %>

  <%= f.submit %>
<% end %>

app/views/photos/edit.html.erb
<%= render :partial => "form" %>

app/views/photos/index.html.erb
<div class="container">
  <ul>
    <% @photos.each do |photo| %>
      <li>
        <%= photo.photo_name %>
        <%= link_to 'Show', photo_path(photo) %>
        <%= link_to 'Edit', edit_photo_path(photo) %>
        <%= link_to 'Destroy', photo_path(photo), method: :delete, data:{ confirm: 'Are you sure?' } %>
      </li>
    <% end %>
  </ul>

  <%= link_to 'New Photo', new_photo_path %>
</div>

app/views/photos/new.html.erb
<%= render :partial => "form" %>

app/views/photos/show.html.erb
<%= @photo.photo_name %>
<%= @photo.tag %>
<%= @photo.date %>
<%= image_tag @photo.file_location.url %>
<%= simple_format(@photo.description) %>

<%= link_to "Back to index", photos_path %>